// The story graph, as data.
//
// Generated by scripts/build-story.mjs on the worldbuilding branch and shipped
// in docs/graph/story.json. It is imported rather than fetched: it is small
// today (96 KB, mostly empty strings) and it is needed on the first frame,
// because the starmap IS the board's affordance. When the beat text lands and
// this grows, it moves to public/ and gets the ontology's lazy-chunk treatment.
//
// ⚠️ ALL IDS IN HERE ARE NUMERIC NODE IDS — the same integers a save stores.
// The content pipeline owns the translation from WordNet synset ids
// (docs/graph/idmap.json); the engine never learns that synset ids exist.
import data from '../../docs/graph/story.json';
import type { StoryGraph } from '../core/types';

export const STORY: StoryGraph = data as StoryGraph;
