// The story graph, as data.
//
// Generated by scripts/build-story.mjs into public/story/. It moved there from
// docs/graph/ because docs/ IS NOT SERVED — nothing could have fetched it at
// runtime.
//
// ⚠️ ALL IDS IN HERE ARE NUMERIC NODE IDS — the same integers a save stores.
// The content pipeline owns the translation from WordNet synset ids
// (docs/graph/idmap.json); the engine never learns that synset ids exist.
//
// THE WIRE FORMAT IS COMPACT, THE RUNTIME SHAPE IS NOT. On the wire a choice
// is `{i,f,to,q?,r?,t?}` with every default omitted; 4,716 choices carrying
// empty labels, empty effects, empty requires and a redundant destination label
// cost 880K. This module expands it once, on load, so every consumer keeps the
// readable shape and nothing downstream has to know.
//
//   i → id · f → frame · l → destination label · t → label (absent: use frame)
//   q.c → required concepts · q.r → required relations (absent: ungated)
//   r → relation (absent: 0, `is a`)
//
// STILL BUNDLED, NOT FETCHED. 243K is imported on the first frame because the
// starmap is the board's only affordance and there is nothing to show without
// it. index.json lists its chunks; when the beat text grows past one chunk this
// should take the ontology's lazy-fetch treatment instead. Flagged, not done.
import manifest from '../../public/story/index.json';
import chunk0 from '../../public/story/s000.json';
import type { StoryGraph, StoryBeat, StoryChoice } from '../core/types';

interface WireChoice {
  i: string;
  f: string;
  to: number;
  l: string;
  t?: string;
  r?: number;
  q?: { c?: number[]; r?: number[] };
}
interface WireBeat {
  id: string;
  at: number;
  atLabel: string;
  depth: number;
  frame: string;
  title?: string;
  body?: string;
  choices: WireChoice[];
}

const expandChoice = (c: WireChoice): StoryChoice => ({
  id: c.i,
  frame: c.f,
  label: c.t ?? '',
  to: c.to,
  toLabel: c.l,
  rel: c.r ?? 0,
  requires: { concepts: c.q?.c ?? [], rels: c.q?.r ?? [] },
});

const wire = (chunk0 as { beats: WireBeat[] }).beats;

export const STORY: StoryGraph = {
  counts: (manifest as { counts: Record<string, number> }).counts,
  frames: (manifest as { frames: Record<string, { title?: string; body?: string; label?: string }> }).frames,
  beats: wire.map(
    (b): StoryBeat => ({
      id: b.id,
      at: b.at,
      atLabel: b.atLabel,
      depth: b.depth,
      frame: b.frame,
      title: b.title ?? '',
      body: b.body ?? '',
      choices: b.choices.map(expandChoice),
    }),
  ),
};

/** Every beat, by the node it is told from. */
export const BEAT_AT = new Map<number, StoryBeat>(STORY.beats.map((b) => [b.at, b]));
