// The story graph, as data.
//
// Generated by scripts/build-story.mjs into public/story/. It moved there from
// docs/graph/ because docs/ IS NOT SERVED — nothing could have fetched it at
// runtime.
//
// ⚠️ ALL IDS IN HERE ARE NUMERIC NODE IDS — the same integers a save stores.
// The content pipeline owns the translation from WordNet synset ids
// (docs/graph/idmap.json); the engine never learns that synset ids exist.
//
// THE WIRE FORMAT IS COMPACT, THE RUNTIME SHAPE IS NOT. On the wire a choice
// is `{i,f,to,q?,r?,t?}` with every default omitted; 4,716 choices carrying
// empty labels, empty effects, empty requires and a redundant destination label
// cost 880K. This module expands it once, on load, so every consumer keeps the
// readable shape and nothing downstream has to know.
//
//   i → id · f → frame · l → destination label · t → label (absent: use frame)
//   q.c → required concepts · q.r → required relations (absent: ungated)
//   r → relation (absent: 0, `is a`)
//
// STILL BUNDLED, NOT FETCHED. 243K is imported on the first frame because the
// starmap is the board's only affordance and there is nothing to show without
// it. index.json lists its chunks; when the beat text grows past one chunk this
// should take the ontology's lazy-fetch treatment instead. Flagged, not done.
import manifest from '../../public/story/index.json';
import chunk0 from '../../public/story/s000.json';
// THE ONLY EDGES A TERMINAL CONCEPT HAS. See "the places with no beat of their
// own" below: without this file a leaf's only ways on are its own siblings, and
// walking one leaf to the next never changes the strip. 48K on the wire, which
// is 20% of the story payload and bought the bottom 89% of the board an exit.
import crosslinks from '../../docs/graph/crosslinks.json';
import type { StoryGraph, StoryBeat, StoryChoice } from '../core/types';

interface WireChoice {
  i: string;
  f: string;
  to: number;
  l: string;
  t?: string;
  r?: number;
  q?: { c?: number[]; r?: number[] };
}
interface WireBeat {
  id: string;
  at: number;
  atLabel: string;
  depth: number;
  frame: string;
  title?: string;
  body?: string;
  choices: WireChoice[];
}

// ---- THE FRAMES ARE THE TEXT ---------------------------------------------
//
// ⚠️ A BEAT WITH NO AUTHORED PROSE RENDERS ITS FRAME. The build script stopped
// pre-rendering the carrier sentences ("the frames go in the manifest instead
// and the renderer fills them") and NOTHING FILLED THEM: 396 of 446 beats and
// 4,622 of 4,716 choices shipped with an empty string, so nine taps in ten
// bought an empty heading over an empty paragraph and a row of bare nouns.
//
// They are filled HERE, once, on load, rather than at the render site: the
// masking renderer, the literacy counter and the aria-label all read the same
// `beat.title` / `choice.label`, and a fallback applied in only one of them is
// how you get a screen that reads one way and teaches another.
type Frame = { title?: string; body?: string; label?: string };
const FRAMES = (manifest as { frames: Record<string, Frame> }).frames;

/** Slots: `{here}` where you stand, `{next}`/`{branch}` where a lane goes.
 *
 *  The slot CONTENTS are what masking hides, so the sentence around them has to
 *  stand on its own — that rule lives with the frames in index.json. Filling is
 *  plain substitution: the ⟦brackets⟧ are already in the frame. */
const fill = (text: string | undefined, here: string, there: string): string =>
  (text ?? '').replace(/\{(here|next|branch)\}/g, (_m, slot: string) =>
    slot === 'here' ? here : there);

const expandChoice = (c: WireChoice, atLabel: string): StoryChoice => ({
  id: c.i,
  frame: c.f,
  // An authored label wins; otherwise the frame's, which is the only thing
  // telling four identically-priced lanes apart — down, across, back up.
  label: c.t ?? fill(FRAMES[c.f]?.label, atLabel, c.l),
  to: c.to,
  toLabel: c.l,
  rel: c.r ?? 0,
  requires: { concepts: c.q?.c ?? [], rels: c.q?.r ?? [] },
});

const wire = (chunk0 as { beats: WireBeat[] }).beats;

export const STORY: StoryGraph = {
  counts: (manifest as { counts: Record<string, number> }).counts,
  frames: FRAMES,
  beats: wire.map(
    (b): StoryBeat => ({
      id: b.id,
      at: b.at,
      atLabel: b.atLabel,
      depth: b.depth,
      frame: b.frame,
      title: b.title ?? fill(FRAMES[b.frame]?.title, b.atLabel, b.atLabel),
      body: b.body ?? fill(FRAMES[b.frame]?.body, b.atLabel, b.atLabel),
      choices: b.choices.map((c) => expandChoice(c, b.atLabel)),
    }),
  ),
};

/** Every beat, by the node it is told from. */
export const BEAT_AT = new Map<number, StoryBeat>(STORY.beats.map((b) => [b.at, b]));

// ---- THE PLACES WITH NO BEAT OF THEIR OWN --------------------------------
//
// A beat exists only for a concept that HAS CHILDREN — 446 of the 4,096 — so
// most destinations on the board are childless. Walking to one used to charge
// the step, hand you the Word, and leave the screen byte-identical, because
// `currentBeat` fell back to the newest held concept that had a beat: the one
// you were already standing in. Three of those in the opening 46 seconds spent
// the whole starting purse and looked exactly like a broken button.
//
// THE LEAF IS ITS OWN KIND OF PLACE. Refusing the walk would delete 3,600
// destinations and the Words they carry; authoring a beat for each is 3,600
// beats of prose nobody will read twice. So a childless concept renders the
// `leaf` frame — "Under ⟦here⟧ the tree stops" — the sentence written for
// exactly this and never once shown, with the ways on from the beat that
// offered it, so arriving is never a room with no doors.
const ARRIVALS = new Map<number, { label: string; from: StoryBeat }>();
for (const b of STORY.beats) {
  for (const c of b.choices) {
    if (BEAT_AT.has(c.to) || ARRIVALS.has(c.to)) continue;
    ARRIVALS.set(c.to, { label: c.toLabel, from: b });
  }
}

/** Every concept's word, from the story data. Both sides of a cross-link need
 *  one and only 446 of 4,096 concepts have a beat to carry it. */
const LABEL = new Map<number, string>();
for (const b of STORY.beats) {
  LABEL.set(b.at, b.atLabel);
  for (const c of b.choices) LABEL.set(c.to, c.toLabel);
}

// ---- WHAT A LEAF HAS THAT ITS SIBLINGS DO NOT ----------------------------
//
// MEASURED, walking eight steps from the opening: every one landed on a leaf,
// every leaf rendered `The Tree Stops`, and every one offered the SAME 21
// buttons — the litter its parent beat had already offered, minus the one just
// taken. Position moved and the screen did not. That is the whole of the "you
// are standing exactly where you were" report.
//
// A leaf's problem is real and not a rendering one: the taxonomy stops there,
// so it HAS no children to offer. What it does have is its definition, and a
// definition names other concepts. `crosslinks.json` holds `[a, b]` = "a's
// gloss contains b's label" — 3,838 exits out of 2,190 of the 3,650 leaves,
// 1,158 of them landing on a concept that DOES branch.
//
// So a leaf's ways on are the words its own definition uses (`sideways`:
// "Follow the definition to ⟦…⟧"), and the siblings stay underneath them as the
// floor — 1,460 leaves have no gloss link and a room with no doors is worse
// than a repetitive one. rel 8 says what the evidence is and claims nothing
// about meaning (`REL_NAMES`).
const REL_NAMED = 8;
const GLOSS_OUT = new Map<number, number[]>();
for (const [a, b] of (crosslinks as { e: number[][] }).e) {
  if (a === undefined || b === undefined || a === b || !LABEL.has(b)) continue;
  const out = GLOSS_OUT.get(a);
  if (out) out.push(b);
  else GLOSS_OUT.set(a, [b]);
}

const glossChoices = (id: number): StoryChoice[] =>
  (GLOSS_OUT.get(id) ?? []).map((to, n) => ({
    id: `x${id}-${n}`,
    frame: 'sideways',
    label: fill(FRAMES.sideways?.label, LABEL.get(id) ?? '', LABEL.get(to)!),
    to,
    toLabel: LABEL.get(to)!,
    rel: REL_NAMED,
    // Ungated on purpose: `requires.rels` is read by nothing in the engine, and
    // a lock nothing enforces is worse than no lock. The gate on these is the
    // step price, like every other lane.
    requires: { concepts: [], rels: [] },
  }));

/** Built once each and kept: the beat is read every frame, and a fresh object
 *  per frame would rebuild the lane strip under the player's thumb. */
const LEAVES = new Map<number, StoryBeat>();

/** The place at a concept: its own beat, else the leaf it is, else nowhere.
 *
 *  Null means the concept is not on the story graph at all — a seed the player
 *  has not arrived at from anywhere, and the caller's cue to keep looking. */
export function placeAt(id: number): StoryBeat | null {
  const authored = BEAT_AT.get(id);
  if (authored) return authored;
  const cached = LEAVES.get(id);
  if (cached) return cached;
  const arrival = ARRIVALS.get(id);
  if (!arrival) return null;
  const own = glossChoices(id);
  const taken = new Set(own.map((c) => c.to));
  const leaf: StoryBeat = {
    id: `leaf-${id}`,
    at: id,
    atLabel: arrival.label,
    depth: arrival.from.depth + 1,
    frame: 'leaf',
    title: fill(FRAMES.leaf?.title, arrival.label, arrival.label),
    body: fill(FRAMES.leaf?.body, arrival.label, arrival.label),
    // Its own gloss links first — those are the ways on nowhere else offers —
    // then the ways on from where you came, minus the one you just took, which
    // would be a lane back to where you are standing.
    choices: [
      ...own,
      ...arrival.from.choices.filter((c) => c.to !== id && !taken.has(c.to)),
    ],
  };
  LEAVES.set(id, leaf);
  return leaf;
}

/** The lanes a concept ADDS to the board — never the ones it inherited.
 *
 *  ⚠️ THE REDUCER'S GATE READS THIS, not `placeAt`. A leaf renders its parent's
 *  siblings so it is never a room with no doors, but those lanes are already on
 *  the board via the parent, which is held by construction. Counting them again
 *  from every leaf would put the same route on the map once per leaf you have
 *  ever stood on. What a leaf genuinely adds is its gloss links. */
export function ownChoices(id: number): StoryChoice[] {
  const authored = BEAT_AT.get(id);
  if (authored) return authored.choices;
  return ARRIVALS.has(id) ? glossChoices(id) : [];
}
